name: Build & Publish for pre-release

on:
  push:
    branches:
      - develop
      - "feature/**"
      - "hotfix/**"
      - "release/**"
      - "!main"

jobs:
  build-publish-prerelease:
    name: Build Develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout template repo (Classic)
        uses: actions/checkout@v3
        with:
          repository: orion-ui/orion-starter
          path: __template-classic__

      - name: Checkout template repo (SetupService)
        uses: actions/checkout@v3
        with:
          repository: orion-ui/orion-starter
          ref: setup-service
          path: __template-setup-service__

      - name: Checkout ci-tools repo
        uses: actions/checkout@v3
        with:
          repository: orion-ui/ci-tools
          path: __ci-tools__

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: npm version "$(BRANCH=${GITHUB_REF_NAME} REPO=${GITHUB_REPOSITORY#*/} node __ci-tools__/npm-version.cjs)" --no-git-tag-version

      - name: Build lib
        run: npm run build

      - name: Publish to NPM for pre-release
        run: npm publish --tag "$(BRANCH=${GITHUB_REF_NAME} node __ci-tools__/npm-sanitize-tag.cjs)" --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
